name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build-MSVC
      run: ./MSVC_build.bat

    - name: Build-MinGW
      run: ./MinGW_build.bat
